
cluster.name: {{cfg.cluster.name}}

cluster.routing.allocation.node_concurrent_recoveries: {{cfg.cluster.routing.allocation.node_concurrent_recoveries}}
cluster.routing.allocation.node_initial_primaries_recoveries: {{cfg.cluster.routing.allocation.node_initial_primaries_recoveries}}
cluster.routing.allocation.same_shard.host: {{cfg.cluster.routing.allocation.same_shard-host}}

{{~#if cfg.cluster.routing.allocation.awareness-attributes}}
cluster.routing.allocation.awareness.attributes: {{cfg.cluster.routing.allocation.awareness-attributes}}
{{~/if}}

node.name: {{cfg.node.name}}
node.max_local_storage_nodes: {{cfg.node.max_local_storage_nodes}}

{{~#if cfg.node.rack_id}}
node.rack_id: {{cfg.node.rack_id}}
{{~/if}}
{{~#if cfg.node.zone}}
node.zone: {{cfg.node.zone}}
{{~/if}}
{{~#if cfg.node.master}}
node.master: {{cfg.node.master}}
{{~/if}}
{{~#if cfg.node.data}}
node.data: {{cfg.node.data}}
{{~/if}}


path.data: {{pkg.svc_data_path}}/{{cfg.path.data}}
path.logs: {{pkg.svc_var_path}}/{{cfg.path.logs}}
path.plugins: {{pkg.svc_var_path}}/{{cfg.path.plugins}}
path.scripts: {{pkg.svc_config_path}}/{{cfg.path.scripts}}

indices.recovery.concurrent_streams: {{cfg.indices.recovery.concurrent_streams}}
indices.recovery.concurrent_small_file_streams: {{cfg.indices.recovery.concurrent_small_file_streams}}
indices.recovery.file_chunk_size: {{cfg.indices.recovery.file_chunk_size}}
indices.recovery.translog_ops: {{cfg.indices.recovery.translog_ops}}
indices.recovery.translog_size: {{cfg.indices.recovery.translog_size}}
indices.recovery.compress: {{cfg.indices.recovery.compress}}
indices.recovery.max_bytes_per_sec: {{cfg.indices.recovery.max_bytes_per_sec}}

{{~#if cfg.indices.fielddata.cache-size}}
indices.fielddata.cache.size: {{cfg.indices.fielddata.cache-size}}
{{~/if}}

indices.breaker.total.limit: {{cfg.indices.breaker.total-limit}}
indices.breaker.fielddata.limit: {{cfg.indices.breaker.fielddata-limit}}
indices.breaker.fielddata.overhead: {{cfg.indices.breaker.fielddata-overhead}}
indices.breaker.request.limit: {{cfg.indices.breaker.request-limit}}
indices.breaker.request.overhead: {{cfg.indices.breaker.request-overhead}}

bootstrap.mlockall: {{cfg.bootstrap.mlockall}}

network.host: {{cfg.network.host}}
http.port: {{cfg.network.port}}

{{~#with cfg.transport}}
transport:
  {{~#if host}}
  host: {{host}}
  {{~/if}}
  {{~#if bind_host}}
  bind_host: {{bind_host}}
  {{~/if}}
  {{~#if publish_host}}
  publish_host: {{publish_host}}
  {{~/if}}
  {{~#if ping_schedule}}
  ping_schedule: {{ping_schedule}}
  {{~/if}}

  {{~#with tcp}}
  tcp:
    port: {{port}}
    {{~#if connect_timeout}}
    connect_timeout: {{connect_timeout}}
    {{~/if}}
    {{~#if compress}}
    compress: {{compress}}
    {{~/if}}
  {{~/with}}
  {{~#with profiles}}
  profiles:
    {{~#each this }}
    {{@key}}:
      port: {{port}}
      {{~#if bind_host}}
      bind_host: {{bind_host}}
      {{~/if}}
      {{~#if publish_host }}
      publish_host: {{publish_host}}
      {{~/if}}
      {{~#if tcp_no_delay}}
      tcp_no_delay: {{tcp_no_delay}}
      {{~/if}}
      {{~#if tcp_keep_alive }}
      tcp_keep_alive: {{tcp_keep_alive}}
      {{~/if}}
      {{~#if reuse_address }}
      reuse_address: {{reuse_address}}
      {{~/if}}
      {{~#if tcp_send_buffer_size }}
      tcp_send_buffer_size: {{tcp_send_buffer_size}}
      {{~/if}}
      {{~#if tcp_receive_buffer_size }}
      tcp_receive_buffer_size: {{tcp_receive_buffer_size}}
      {{~/if}}
    {{~/each }}
  {{~/with}}
{{~/with}}

discovery.zen.fd.ping_timeout: {{cfg.discovery.zen_fd_ping_timeout}}
discovery.zen.ping.multicast.enabled: {{cfg.discovery.ping_multicast_enabled}}
discovery.zen.ping.unicast.hosts: [{{#each svc.members ~}} "{{sys.ip}}", {{/each ~}}]

discovery.zen.minimum_master_nodes: {{cfg.discovery.minimum_master_nodes}}

gateway.recover_after_nodes: {{cfg.gateway.recover_after_nodes}}
gateway.expected_nodes: {{cfg.gateway.expected_nodes}}
gateway.expected_master_nodes: {{cfg.gateway.expected_master_nodes}}
gateway.expected_data_nodes: {{cfg.gateway.expected_data_nodes}}
{{~#if cfg.gateway.recover_after_time}}
gateway.recover_after_time: {{cfg.gateway.recover_after_time}}
{{~/if}}

action.destructive_requires_name: {{cfg.action.destructive_requires_name}}

index.number_of_replicas: {{cfg.index.number_of_replicas}}
index.number_of_shards: {{cfg.index.number_of_shards}}

{{#if cfg.plugins.cloud_aws_signer ~}}
cloud.aws.signer: {{cfg.plugins.cloud_aws_signer}}
{{/if ~}}
